### ISSUE TITLE
Aqara Wall Switch (QBKG11LM, QBKG12LM, neutral) Date.parse() error

### ISSUE THREAD

**Issue by martynwendon** [guyeeba/Hubitat#1]
I am seeing the following error in the HE logs with HE firmware 2.0.6.112:

`2019-02-26 14:28:45.154 errorgroovy.lang.MissingMethodException: No signature of method: static java.util.Date.parse() is applicable for argument types: (java.lang.String, java.util.Date) values: [yyyy-MM-dd'T'HH:mm:ssZ, Tue Feb 26 14:28:45 GMT 2019]
Possible solutions: parse(java.lang.String), parse(java.lang.String, java.lang.String), parse(java.lang.String, java.lang.String, java.util.TimeZone), wait(), clone(), any() on line 522 (parse)`

Hopefully a simple fix?

**Comment by guyeeba** [comment]
Hi, I updated the code: now it uses epoch instead of formatted time to get rid of format issues

**Comment by martynwendon** [comment]
Thanks, that's sorted it :-)
